### ISSUE TITLE
Apple-specific suggestions

### ISSUE THREAD

**Issue by Askaniy** [levinli303/astroweather-localization#12]
I'm not even have Apple devices to test localization, but here are some notes:
- `...` to `…`?
- "...location service is enabled on your iPhone and permission is...", Astroweather supports iPads, right? I replace it with `device` in translation
- analogue for `fail_to_get_data` from Android is needed
- where is star sorting by name? `riset_sort_name` in Android
- added missing Chamaeleon to the EN file
- what's with titles in files of different languages? maybe standardization is needed?

**Comment by levinli303** [comment]
1. fair, i will change it
2. please try to use iPhone/iPad instead of device. i will fix in the other languages
3. https://github.com/levinli303/astroweather-localization/blob/4443b147e49865e4f4bbdd4a63c1965617e14d0f/iOS/en/Shared/Localizable.strings#L1970 they both mean network request error underneath
4. https://github.com/levinli303/astroweather-localization/blob/4443b147e49865e4f4bbdd4a63c1965617e14d0f/iOS/en/Shared/Localizable.strings#L28 let me know if disambiguation is needed
5. thanks, please do add it in the change you will commit
6. see below

the iOS localization has multiple files because of history. i've tried to move most of the strings to Shared/Localizable but some will remain in other folders/files and they have to have follow name conventions.

App/InfoPlist.strings for metadata about the app, name, permission clarification

AstroweatherToday folder is for the old pre-iOS 14 style widget that i plan to remove in the future
AstroweatherToday/InfoPlist.strings, metadata about the widget
AstroweatherToday/MainInterface.strings, the UI was done in old school fashion and comes with this strings file for localization. since i plan to remove it, i will not try to migrate this widget

AstroweatherWidget folder is for iOS14+ style widget
AstroweatherWidget/AstroweatherWidget.strings is the file generated for localization for widget configuration. on iOS 17+ i plan to move it to new implementation (means the strings will be duplicated somewhere), but this file will be kept for compatibility indefinitely

Shared/Localizable.strings is for all the strings shared among the app, the old widget and the new widget.

**Comment by Askaniy** [comment]
1, 2, 6) ok
3) sorry, I'm about `astro_title_time_no`
![изображение](https://github.com/levinli303/astroweather-localization/assets/44873271/616d0c55-f12e-4c45-9e7f-eec5f04ffc2d)
4) yes, disambiguation is needed for Russian
7) I don't see text for Precipitation map, as on Android

**Comment by levinli303** [comment]
1 is done in https://github.com/levinli303/astroweather-localization/commit/a55b94a72a8fd525504ba8c5058b183d444430ef
3. this is a placeholder on Android not used on iOS. iOS uses a combination of "Report released at: %@" with "N/A"
4. added in https://github.com/levinli303/astroweather-localization/commit/b608e34d956d2c83313641f3a8c09a2b39f4fef1
7. where do you find it i cannot find this string in either iOS or Android

**Comment by Askaniy** [comment]
3. I know, the placeholder use on Android made the translation more concise. In fact, the current iOS translation works, just less concisely.
7) I mean line 172 ↓, and it's shown in app too
![изображение](https://github.com/levinli303/astroweather-localization/assets/44873271/46123e53-e912-4a31-a1a6-769046dd5750)

**Comment by levinli303** [comment]
https://github.com/levinli303/astroweather-localization/blob/0cb4d9a5cef86e9c72d8c9b5cdce74346034cf82/iOS/en/Shared/Localizable.strings#L1832 is it this?

**Comment by Askaniy** [comment]
Not this, above it:
![изображение](https://github.com/levinli303/astroweather-localization/assets/44873271/1c9ab3db-e6bf-40d7-9d4e-c9fb2187f69c)
Just this is the question. Android has one more weather map than iOS.

**Comment by levinli303** [comment]
https://github.com/levinli303/astroweather-localization/blob/0cb4d9a5cef86e9c72d8c9b5cdce74346034cf82/iOS/en/Shared/Localizable.strings#L95

**Comment by Askaniy** [comment]
I assumed that here one line is responsible for two translations. For the Russian translation, this is not critical, there is no ambiguity. So I leave it up to you

**Comment by levinli303** [comment]
i will adopt better keys/comments for iOS when i have time. so let's leave them as they are.
